sonar.projectKey=revshop
#Name of the sonarqube project. Not the eclipse project.
sonar.projectName=RevShop
sonar.projectVersion=1.0
#All the sources files are available inside the current folder and inside it's subfolders.
sonar.sources=.
sonar.host.url=http://localhost:9000
sonar.login=squ_4405fbf1dfa6899e18136bd137da3f25f05cbf2a
sonar.java.binaries=target/classes