sonar.projectKey=revshop
#Name of the sonarqube project. Not the eclipse project.
sonar.projectName=RevShop
sonar.projectVersion=1.0
#All the sources files are available inside the current folder and inside it's subfolders.
sonar.sources=.
sonar.host.url=http://localhost:9000
sonar.login=squ_0c732328fb5b71de6e25d33983558e8c9ce3b978
sonar.java.binaries=target/classes