spring.application.name=revshop
# Server Port
server.port=8090

# ======================
# ORACLE DATABASE CONFIG
# ======================
spring.datasource.url=jdbc:oracle:thin:@localhost:1521/XEPDB1
spring.datasource.username=revshop
spring.datasource.password=revshop123
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

# ======================
# JPA & HIBERNATE CONFIG
# ======================
# Since we will create tables using Entities
spring.jpa.hibernate.ddl-auto=update
# IMPORTANT for lowercase table names in Oracle
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl


# Show SQL queries in console (debugging)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Oracle Dialect (IMPORTANT)
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect

# ======================
# LOGGING (OPTIONAL DEBUG)
# ======================
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql=TRACE

# ======================
# THYMELEAF (Frontend)
# ======================
spring.thymeleaf.cache=false
#spring.thymeleaf.cache=false
#spring.devtools.restart.enabled=true
#spring.devtools.livereload.enabled=true